### ISSUE TITLE
Add dynamic guards to the fallback function

### ISSUE THREAD

**Issue by julien-devatom** [Rubilmax/executooor#1]
## Feature Request
- you cannot control who is calling the i-th fallback function. The idea is to have a dynamic way to say "I want this i-th fallback to be  called by address 0xdead"
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- use the calldata to add an address at the beginning (padded into the first slot) that is the address to check into the fallback. If it is address 0, then bypass the check. 

**Describe alternatives you've considered**

## Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Rubilmax** [comment]
Fixed in https://github.com/Rubilmax/multidelegatecall/commit/9e2357d8b8037f6a4f13bc66cc361d9d7b398244
